services:
  gateway:
    build: .
    container_name: mini-redis-gateway
    restart: unless-stopped
    environment:
      - PORT=8080
      - REDIS_HOST=mini-redis
      - REDIS_PORT=6380
      - JAVA_TOOL_OPTIONS=-Xmx256m
    networks:
      - mini-redis_default

  caddy:
    image: caddy:alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from api.miniredis.suleman.app --to gateway:8080
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mini-redis_default
    depends_on:
      - gateway

volumes:
  caddy_data:
  caddy_config:

networks:
  mini-redis_default:
    external: true
